export const GET_ALL_PLAYLISTS_LOADING = "GET_ALL_PLAYLISTS_LOADING";
export const GET_ALL_PLAYLISTS_SUCCESS = "GET_ALL_PLAYLISTS_SUCCESS";
export const GET_ALL_PLAYLISTS_FAILURE = "GET_ALL_PLAYLISTS_FAILURE";
export const GET_FEEDS_BY_PLAYLIST_LOADING = "GET_FEEDS_BY_PLAYLIST_LOADING";
export const GET_FEEDS_BY_PLAYLIST_SUCCESS = "GET_FEEDS_BY_PLAYLIST_SUCCESS";
export const GET_FEEDS_BY_PLAYLIST_FAILURE = "GET_FEEDS_BY_PLAYLIST_FAILURE";
